### ISSUE TITLE
frontend - Fix: Get user favorties is in wrong format

### ISSUE THREAD

**Issue by Curtis-Thomas** [group13-Advanced-Web-Project/Movie-Central#148]
![Image](https://github.com/user-attachments/assets/ca9d56ed-4ef9-48c6-a21a-24acb75f16cf)

Currently:

the request is being made to the wrong endpoint with the wrong data

https://movie-app-2sz1.onrender.com/favorites/all

Desired:

The call should be made to:

https://movie-app-2sz1.onrender.com/favorites/    {USER ID GOES HERE}

Eg. https://movie-app-2sz1.onrender.com/favorites/auth0|67407d7aafb1677163ea897

![Image](https://github.com/user-attachments/assets/92b63cce-8757-4616-b241-7c403dd4d799)

**Comment by Curtis-Thomas** [comment]
@t3idma00 The method you are using on the profile page is correct and can be used here as well.

**Comment by t3idma00** [comment]
With the bugs fixing referring to #159 this bug has also been fixed. ![Image](https://github.com/user-attachments/assets/5a57d05f-95b9-4590-b7b0-29555f56fbd7)

**Comment by Curtis-Thomas** [comment]
@t3idma00 I am still getting the error, is your screenshot from the live site?

![image](https://github.com/user-attachments/assets/aa7b6ac2-9850-432f-a328-f04cb0cf3337)

![image](https://github.com/user-attachments/assets/3c2b074e-9769-46b6-9f92-00db29547e21)
![image](https://github.com/user-attachments/assets/d7c3a4b7-9e58-46bd-a73e-d4a689118142)

**Comment by Curtis-Thomas** [comment]
@t3idma00 this issue is still happening for me, caused by:

frontend/src/pages/moviepage/MoviePage.js

line 57

![Image](https://github.com/user-attachments/assets/6442d869-4e71-4792-a0ec-775f79fa6748)


![Image](https://github.com/user-attachments/assets/e92daaaa-8aa6-48af-bb8c-132b039fe635)

**Comment by Curtis-Thomas** [comment]
@t3idma00 maybe this is the problem, is this code supposed to be commented out?

![Image](https://github.com/user-attachments/assets/08830cc1-8ba2-4a44-8e9c-a15cba121bbd)
