### ISSUE TITLE
frontend: Fix - public profile data not passed correctly

### ISSUE THREAD

**Issue by Curtis-Thomas** [group13-Advanced-Web-Project/Movie-Central#149]
![Image](https://github.com/user-attachments/assets/4d3b2cde-a57d-4e8a-9463-ccdb95414eb4)

Currently:

PublicProfile.js

location.state and storedData are not correctly getting/storing user data, so the public profile is showing empty

![Image](https://github.com/user-attachments/assets/02ef3853-e072-438e-91a3-4e37a139c72f)

Desired:

Correctly show data on the public page

**Comment by t3idma00** [comment]
Now favorite movies and user details are fetched from the backend.

 ![Image](https://github.com/user-attachments/assets/ab153e90-f9fa-4f01-936b-3cf230411aaf)

![Image](https://github.com/user-attachments/assets/ced2188d-97cf-4c59-baad-f2df0acf2e81)
