### ISSUE TITLE
backend: bug - GET reviews/   returns excessive user information

### ISSUE THREAD

**Issue by Curtis-Thomas** [group13-Advanced-Web-Project/Movie-Central#195]
![Image](https://github.com/user-attachments/assets/6ed39f21-4fed-43a4-9419-9d6cb3a34079)

Currently:

Endpoint GET /reviews/ 
returns more user information than required with no auth required.

Desired:

Only return required user account data and apply authorization if needed.

**Comment by SteffiEaint** [comment]
Which authentication should I use? Auth0 based authentication? In that case, I don't know the necessary keys. Or do I just get rid of the user id in the get reviews output as it's not necessarily needed?
